### ISSUE TITLE
[Request] Some new conditions

### ISSUE THREAD

**Issue by ghost** [The-Fireplace-Minecraft-Mods/Block-Replacer#1]
I'm not at home, so I can't download the mod and inspect the config, but from the code it looks like there aren't really many/any conditions to determine when a block should be replaced, so here are my suggestions;

- Y minimum
- Y maximum
- Biome

I figure these will provide a good basis to do things like replace all tall grass in savanna biomes with double tall grass, or replace all lava above Y 64 in snowy biomes with obsidian, or any number of other biome specific things.

**Comment by The-Fireplace** [comment]
Done in 2.0.0
