### ISSUE TITLE
[1.14.4] Hang during world creation

### ISSUE THREAD

**Issue by Efimero** [The-Fireplace-Minecraft-Mods/Block-Replacer#13]
Minecraft: 1.14.4
Forge: 28.1.96
Block Replacer: 2.1.1

Starting a new world in singleplayer hanges at the chunk viewer screen when the first chunk goes white.

Config file (in defaultconfigs) and logs: https://gist.github.com/Efimero/033453455ed09dbbf1262961e1d67ef5

**Comment by The-Fireplace** [comment]
I believe this is caused by #12 .
