### ISSUE TITLE
Mod not reporting cause of improper configuration

### ISSUE THREAD

**Issue by Pdan4** [The-Fireplace-Minecraft-Mods/Block-Replacer#17]
Minecraft 1.12.2, Forge 14.23.5.2847, Block Replacer 2.2.0.

Summary: Mod says "see the logs" but doesn't put any content in.

Trying to replace regular minecraft:water with terrafirmacraft waters.

Currently all logs only say "See the logs to find out what wasn't configured properly."... but none of the logs say anything else. 

I suspect that the biome names might not be right but I don't know.

**Comment by Pdan4** [comment]
Discovered circumstance: Mod does not tell user that selected replacement block is risky and that the operation has been cancelled.

**Comment by The-Fireplace** [comment]
Version 2.3.0 should fix this.
