### ISSUE TITLE
Replacements missing stripes of land

### ISSUE THREAD

**Issue by PCSpinner** [The-Fireplace-Minecraft-Mods/Block-Replacer#19]
**Describe the bug**
Block replacements are missing random 8x8 patches, usually lined up together.

**To Reproduce**
1. Setup a replacement
2. Log in

**Logs/Screenshots/Videos**
config:  https://pastebin.com/NnVW1Wkz
screenshots:   https://imgur.com/a/Bun1EZT   

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: 2.2.0
 - Forge 1.12.2-14.23.5.2847
 - Quark-r1.6-178

**Comment by The-Fireplace** [comment]
Try again with 2.3.0 and comment if this is still an issue.
