### ISSUE TITLE
[Request] Replacing blocks next to block of choice

### ISSUE THREAD

**Issue by pirone2** [The-Fireplace-Minecraft-Mods/Block-Replacer#2]
Would be a nice feature to be able to change blocks based on what is next to them.
Like, making it so that whenever the world generates a crafting table, it replaces the block under it with a torch, for example.

**Comment by The-Fireplace** [comment]
I'll keep this in consideration, but I don't see this happening in the foreseeable future. Doing stuff like that is borderline structure generation. After all, if you can configure a few blocks around any one block in the world, why not generate entire structures around one block? And that's a little out of scope for this mod.

**Comment by ilvrak** [comment]
i need to replace all stone blocks, which connects Lava with Basalt.
like in Chisel mod, but i dont need whole Chisel - only edging lava pockets with basalt stone from quark.
