### ISSUE TITLE
Tropicraft Water not replcing Minecraft Water

### ISSUE THREAD

**Issue by ZGNRDev-ThomS** [The-Fireplace-Minecraft-Mods/Block-Replacer#20]
**Describe the bug**
Trying to replace Minecraft's water with the Tropics water of Tropicraft will result in a crash saying that WgBR is improperly configured

**To Reproduce**
1. Configure WgBR with 
2. Replace Block: [minecraft:water]
3. Replace Block with: [tropicraft:tropicsWater]
4. See error when loading a world

Log File: edited most of it out as it's irrelevant
https://pastebin.com/n20fsTXa

 - Minecraft: [1.12.2]
 - Mod Version: [2.2.0]
 - Forge [Forge 14.23.5.2847]

**Comment by The-Fireplace** [comment]
Thanks for posting this here. Would you be willing to make a paste of your config file and provide a link to that as well? This could help speed up the process of finding and fixing the issue.

**Comment by ZGNRDev-ThomS** [comment]
Of course, here you go
https://pastebin.com/ArgqdbKv

**Comment by VinterNacht** [comment]
I am having this exact same issue.  Does not seem to like to replace Minecraft:Water with anything but Minecraft:Water

**Comment by The-Fireplace** [comment]
Try again with 2.3.0 and comment if this is still an issue.
