### ISSUE TITLE
Air is occasionally not being filled in with water.

### ISSUE THREAD

**Issue by SnakekillerX** [The-Fireplace-Minecraft-Mods/Block-Replacer#21]
I'm using The Midnight dimension mod and I've decided to flood the entire lower cavern sections of this dimension.  The majority of it is flooded as expected, but in the larger cavern areas it is failing to fill several 16 x 16 x 16 cubes of air.

There are 3 or 4 of them in this screenshot.  Sometimes they form right next to one another to make a 16 x 16 x 32 pocket of air.

I've also tried to change lateReplacement higher than 0 but the water breaks even worse at anything higher than 1.

Thanks for looking into it.

![image](https://user-images.githubusercontent.com/8332196/80852471-d6316b00-8bf6-11ea-9eee-02ce264cacd0.png)

# Configuration file

general {
    # This is the Biome Black/Whitelist. If it contains *, it is a blacklist. Otherwise, it is a whitelist.
    S:biomefilter <
        *
        *
        *
        *
        *
        *
        *
        *
        *
     >

    # Increase the precision of the biome filter. This may reduce performance.
    B:biomeprecision=true

    # This is the Dimension Black/Whitelist. If it contains *, it is a blacklist. Otherwise, it is a whitelist.
    S:dimension_list <
        4
        4
        4
        4
        4
        4
        4
        4
        4
     >

    # Runs the replacement this many ticks after the chunk is generated. Use this if you're having issues with some blocks not being replaced. I strongly recommend that you do not set this above 10. 2-5 should be plenty.
    I:lateReplacement=0

    # The server's locale
    S:locale=en_us

    # The highest Y value the block should be replaced at
    # Min: -1
    # Max: 256
    I:maxy <
        60
        23
        23
        23
        23
        23
        23
        23
        23
     >

    # The lowest Y value the block should be replaced at
    # Min: -1
    # Max: 256
    I:miny <
        -1
        -1
        -1
        1
        1
        1
        -1
        -1
        -1
     >

    # Multiplies the block removal chance by the block's y-value.
    B:multiplychance <
        false
        false
        false
        false
        false
        false
        false
        false
        false
     >

    # Prevent the world from loading if the mod is improperly configured. This is to prevent terrain from generating without the intended configuration.
    B:preventLoadOnFailure=false

    # The block id to replace.
    S:replaceblock <
        minecraft:air
        midnight:nightstone
        midnight:midnight_mycelium
        midnight:midnight_mycelium
        midnight:midnight_mycelium
        midnight:midnight_mycelium
        midnight:midnight_mycelium
        midnight:midnight_mycelium
        midnight:nightstone
     >

    # The block meta to replace. Use -1 for the block's default state.
    I:replaceblockmeta <
        -1
        -1
        -1
        -1
        -1
        -1
        -1
        -1
        -1
     >

    # Changing this will allow Block Replacer to run again on existing chunks. Useful for doing retrogen on world you've already run the mod on. Back up your world before changing this.
    S:replacementChunkKey=DEFAULT_REPLACE_KEY

    # What percentage of the blocks get replaced. 0.0D = 0%, 1.0D = 100%
    # Min: 0.0
    # Max: 1.0
    D:replacepercent <
        1.0
        1.0
        0.1
        0.1
        0.1
        0.1
        0.1
        1.0
        0.15
     >

    # The block id to replace the block with.
    S:replacewith <
        minecraft:water
        minecraft:gravel
        better_diving:seagrass
        better_diving:creepvine
        better_diving:creepvine_seed
        better_diving:creepvine_top
        better_diving:seagrass_tall_bottom
        minecraft:water
        midnight:midnight_mycelium
     >

    # The block meta for the replacement block. Use -1 for the block's default state.
    I:replacewithmeta <
        -1
        -1
        -1
        -1
        -1
        -1
        -1
        -1
        -1
     >

    # Enables using blocks that might crash/lag the game if used to replace other blocks. Enable at your own risk.
    B:riskyblocks=true
}

**Comment by The-Fireplace** [comment]
Try again with version 2.3.0 and comment if this is still an issue.
