### ISSUE TITLE
Numbered Rows + Block Added (In game GUI)

### ISSUE THREAD

**Issue by SnakekillerX** [The-Fireplace-Minecraft-Mods/Block-Replacer#22]
Often while adding a block replacement (or sometimes several at once) I end up missing adding a block entry in one of the 10 categories.

Also, when going back to edit a block its difficult to tell which one is which and you have to keep counting down the row of entries to modify the correct one.

For example:

![image](https://user-images.githubusercontent.com/8332196/80855631-bad35980-8c10-11ea-8caa-71bd4f5d60ed.png)

It would be nice to have the rows numbered on the left so you can more easily keep track of which block you are modifying.  It could also take the name from the block you are adding and label it next to that numbered row.

I think would save people lot of time and help people from making simple mistakes.

**Comment by The-Fireplace** [comment]
I think this is a good idea, but I won't be messing with the config GUI for 1.12.2. Maybe once a config GUI is available for 1.15.2+, if it is more flexible, I may consider something like this, but I recommend editing from the config file for now.
