### ISSUE TITLE
Enable/Disable and Duplicate/Insert/Delete/Re-Arrange Rules - (In game GUI)

### ISSUE THREAD

**Issue by SnakekillerX** [The-Fireplace-Minecraft-Mods/Block-Replacer#23]
Sometimes you are happy with how something is setup but want to try some different combinations without necessarily deleting what you've already setup.

It would be nice to have an enable/disable section which you can from there toggle which rules are on/off out of the blocks you've already setup.  This could then comment out each entry for the block's rule in all 10 categories.

Additionally, a way to insert a rule between other rules (due to order of generation) would be great as it saves a lot of manually copy/pasting things in a text editor.

Having an insert, delete and re-arrange rules order option would be really great as well.
Will help you to manually organize your rules by dimension, or whatever else you want.

**Comment by The-Fireplace** [comment]
I think this is a good idea, but I won't be messing with the config GUI for 1.12.2. Maybe once a config GUI is available for 1.15.2+, if it is more flexible, I may consider something like this, but I recommend editing from the config file.
