### ISSUE TITLE
failing to Replace Apples+ blocks [1.12.2]

### ISSUE THREAD

**Issue by Shibva** [The-Fireplace-Minecraft-Mods/Block-Replacer#28]
**Describe the bug**
when I atempt to replace the oregen of the ruby and Bedrock fragment ore from apples+ (becasue for some reason, they dont have a config to disable such) when I set it to replace sed blocks and still keep finding it even after I set the late replacement to 300 just to see if its working and its not.

**To Reproduce**
1. install this mod along with Apples+
2. set it to replace stone with applesplus:rubyore
3. save and load in world
4. dig around or use some other mod like advanced x ray or Scanable to see that the rubies are still apearing and not being replaced

**Logs/Screenshots/Videos**
Providing logs can be helpful in solving issues. If you crashed, you _must_ provide a crash report and/or a log file. Logs are usually named something like latest.log, debug.log, fml-client-latest.log, or fml-server-latest.log and can be found in the logs folder. If you have one of these, please paste it to [Ubuntu Pastebin](https://paste.ubuntu.com/) or [Pastebin](https://pastebin.com/) and provide the link here. Do *not* attach the log file directly.

**Versions (please complete the following information, do *NOT* say "latest"):**
 - Minecraft: 1.12.2
 - Mod Version: 2.2.0
 - Forge: 14.23.5.2854
 
 Original done in 300+ modpack but was able to reproduce results with just this mod and Apples+

**Comment by Shibva** [comment]
picture of the ore still being present dispite setting it to replace it with minecraft:air 
(same results with minecraft:stone]
![image](https://user-images.githubusercontent.com/38770780/111015064-000a0100-8375-11eb-8a12-8697230c1f0e.png)

**Comment by The-Fireplace** [comment]
I believe it. This mod isn't perfect, and it won't be able to replace everything that every mod generates. I've done what I can to mitigate it with late replacement, etc. Hopefully I'll be able to improve this more when I update to a newer MC version.
