### ISSUE TITLE
Not working with MCreator mods 

### ISSUE THREAD

**Issue by vengray** [The-Fireplace-Minecraft-Mods/Block-Replacer#30]
I tested this with these three mods trying to replace the copper ore spawning in the caves and cliffs mod with stone, netherrack, air and iron blocks. I tried replacing the mudstone that spawned everywhere in the village and pillage mod with stone. and i tried replacing the quark basalt with the nether update basalt. all useing mcreator mods. its worked with other mods i use. 

caves and cliffs mod
 https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs/files/3095803

village and pillage mod
https://www.curseforge.com/minecraft/mc-mods/village-and-pillage-and-pillage-and-village-1-12-2/files/2831448

nether update mod
https://www.curseforge.com/minecraft/mc-mods/netherite-1-16-nether-overhaul/files/2879582

this was using 1.12.2 forge version 14.23.5.2855

https://user-images.githubusercontent.com/85702465/121609470-ed5da180-ca21-11eb-9fb5-f32ec564133a.png

**Comment by The-Fireplace** [comment]
All three of those mods are closed source and All Rights Reserved, so I cannot do anything special to add support for them. Also, 1.12.2 is no longer supported.
