### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by Origins-Eternity** [The-Fireplace-Minecraft-Mods/Block-Replacer#31]
**Describe the bug**
When I entered a world, my game crashed.

**To Reproduce**
1. I edit the mod's config
2. I start my game
3. I enter a world

**Logs/Screenshots/Videos**
Crash Report: [https://pastebin.com/XN7YJ2WT](https://pastebin.com/kiFf5h55)
config: [https://pastebin.com/XN7YJ2WT](https://pastebin.com/XN7YJ2WT)

**Versions**
 - Minecraft: [1.12.2]
 - Mod Version: [2.3.0]
 - Forge [Forge 14.23.5.2854]

**Comment by The-Fireplace** [comment]
Because you have four entries for replaceblock / replacewith, the other options need to have four things on the list too, even if it's four of the same value.

**Comment by Origins-Eternity** [comment]
> Because you have four entries for replaceblock / replacewith, the other options need to have four things on the list too, even if it's four of the same value.

Ok, thanks for your answer.
