### ISSUE TITLE
Crash with minecraft:air unless riskyblocks=true

### ISSUE THREAD

**Issue by Leggerrr** [The-Fireplace-Minecraft-Mods/Block-Replacer#5]
There's a crash if you use minecraft:air unless riskyblocks=true.

**Comment by The-Fireplace** [comment]
Crash Report:
https://paste.ubuntu.com/p/N5yCXXggHD/
Config:
https://paste.ubuntu.com/p/XckfH9TZhS/
Relevant Discord Conversation:
https://paste.ubuntu.com/p/DDZ342VxjX/
