### ISSUE TITLE
Cannot replace minecraft:tall_grass with minecraft:air

### ISSUE THREAD

**Issue by Leggerrr** [The-Fireplace-Minecraft-Mods/Block-Replacer#6]
Solid blocks appear to work fine, but replacing minecraft:tall_grass does not work. There's no crash in place. Just nothing happens.

**Comment by The-Fireplace** [comment]
What mod version and mc version?

**Comment by The-Fireplace** [comment]
Alright, it seems that grass is generated after the block replacement runs. Also, in 1.12.2, you'd replace minecraft:double_plant states 2 and 10

**Comment by The-Fireplace** [comment]
This should be possible now with version 2.2.0
