### ISSUE TITLE
Replace blocks generated in structures

### ISSUE THREAD

**Issue by Loriborn** [The-Fireplace-Minecraft-Mods/Block-Replacer#7]
At the moment, both vanilla and mod added structures are not affected by block replacement.

**Comment by The-Fireplace** [comment]
What mod version and MC version did you test with?

**Comment by Loriborn** [comment]
Currently in 12.2. Attempting to use WBBR on furnaces/workbenches doesn't work as intended, as villages and structures added by mods are not affected. Naturally generated blocks, such as bedrock, stone, etc., work as intended, but the replacement seems to run pre-generation of structures, whether those are mod-added or vanilla.

**Comment by The-Fireplace** [comment]
This might be fixed with the new generation method I'm using in 1.13.2. If you'd like to give that a try and see if it affects Vanilla structures, I'd be willing to backport it at some point so 1.12.2 behaves the same way.

**Comment by The-Fireplace** [comment]
This might be fixed with the new generation method I'm using in 1.13.2. If you'd like to give that a try and see if it affects Vanilla structures, I'd be willing to backport it at some point so 1.12.2 behaves the same way.

**Comment by The-Fireplace** [comment]
Alright, backported the changes to 1.12.2. If this doesn't fix it, it isn't going to happen.
